
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Feb 23 18:59:21 CET 2017
//----------------------------------------------------

package plic.analyse;

/** CUP generated class containing symbol constants. */
public class CodesLexicaux {
  /* terminals */
  public static final int IDF = 17;
  public static final int OU = 15;
  public static final int CLASS = 23;
  public static final int PLUS = 2;
  public static final int SUP = 10;
  public static final int VIRGULE = 9;
  public static final int NON = 16;
  public static final int MOINS = 3;
  public static final int INF = 11;
  public static final int POINTVIRGULE = 8;
  public static final int PARFER = 7;
  public static final int ENTIER = 22;
  public static final int EOF = 0;
  public static final int MULT = 4;
  public static final int EGALEGAL = 12;
  public static final int DIV = 5;
  public static final int CONSTANTEBOOL = 19;
  public static final int ET = 14;
  public static final int PRIVEE = 21;
  public static final int error = 1;
  public static final int PAROUV = 6;
  public static final int DIFF = 13;
  public static final int CONSTANTEINT = 18;
  public static final int FIN = 24;
  public static final int PUBLIQUE = 20;
}

