
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Apr 25 20:01:41 CEST 2017
//----------------------------------------------------

package plic.analyse;

/** CUP generated class containing symbol constants. */
public class CodesLexicaux {
  /* terminals */
  public static final int IDF = 19;
  public static final int EGAL = 13;
  public static final int OU = 17;
  public static final int CLASS = 25;
  public static final int PLUS = 2;
  public static final int SUP = 11;
  public static final int ECR = 29;
  public static final int NOUVEAU = 28;
  public static final int ALORS = 32;
  public static final int POINT = 10;
  public static final int VIRGULE = 9;
  public static final int NON = 18;
  public static final int FSI = 34;
  public static final int MOINS = 3;
  public static final int INF = 12;
  public static final int POINTVIRGULE = 8;
  public static final int PARFER = 7;
  public static final int SINON = 33;
  public static final int ENTIER = 24;
  public static final int EOF = 0;
  public static final int MULT = 4;
  public static final int EGALEGAL = 14;
  public static final int DIV = 5;
  public static final int CONSTANTEBOOL = 21;
  public static final int SI = 31;
  public static final int ET = 16;
  public static final int PRIVEE = 23;
  public static final int error = 1;
  public static final int PAROUV = 6;
  public static final int CONSTANTECHAINE = 30;
  public static final int DIFF = 15;
  public static final int CONSTANTEINT = 20;
  public static final int DEBUT = 26;
  public static final int FIN = 27;
  public static final int PUBLIQUE = 22;
}

